[package]
name = "geekera"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.27.0", features = ["full"] }
serde = { version = "1.0.160", default-features = false, features = ["derive"] }
anyhow = { version = "1.0.70" }

[features]
default = [
    "runtime"
]
runtime = []